import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  serverExternalPackages: ["@mastra/*"],
  images: {
    domains: [
      'pc.watch.impress.co.jp',
      'k-tai.watch.impress.co.jp',
      'techcrunch.com',
      'www.gizmodo.jp',
      'assets.st-note.com',
      'cdn-ak-scissors.b.st-hatena.com',
      'ascii.jp',
      'www.itmedia.co.jp',
      'japan.cnet.com',
      'news.mynavi.jp',
      'www.publickey1.jp',
      'prtimes.jp',
      'www.sbbit.jp',
      'www.nikkei.com',
      'www.nikkeibp.co.jp',
      'www.atmarkit.co.jp',
      'www.bcnretail.com',
      'www.watch.impress.co.jp',
      'www.nikkei.com',
      'www.nikkeibp.co.jp',
      'www.atmarkit.co.jp',
      'www.bcnretail.com',
      'www.watch.impress.co.jp',
      'cdn.techable.jp',
      'image.itmedia.co.jp',
      'www.itmedia.co.jp',
      'www.gizmodo.jp',
      'assets.media-platform.com',
      'media.loom-app.com',
      'www.sbbit.jp',
      'news.mynavi.jp',
      'ascii.jp',
      'cdn-ak-scissors.b.st-hatena.com',
      'assets.st-note.com',
      'prtimes.jp',
      'japan.cnet.com',
      'publickey1.jp',
      'www.publickey1.jp',
      'www.nikkei.com',
      'www.nikkeibp.co.jp',
      'www.atmarkit.co.jp',
      'www.bcnretail.com',
      'www.watch.impress.co.jp',
      'cdn-ak-scissors.b.st-hatena.com',
      'assets.st-note.com',
      'prtimes.jp',
      'japan.cnet.com',
      'publickey1.jp',
      'www.publickey1.jp',
    ],
  },
  /* config options here */
};

export default nextConfig;
